### PR TITLE
Added note about starting HTTPoison

### PR DESCRIPTION
**Pull request by coryodaniel**
I fumbled around for about 15 minutes trying to figure out why the library was returning errors... figured I'd share the solution to my mistake :D

### CODE REVIEW

**Comment by jkakar** [comment]
Thanks for taking the time to debug this and push these changes @coryodaniel, but I think you actually want to start `aws` and not `httpoison`.  Starting `aws` should start [all dependent applications](https://github.com/jkakar/aws-elixir/blob/master/mix.exs#L21-L23) (and will keep working when/if we add more dependencies to the `aws` application in the future).

**Comment by coryodaniel** [comment]
Well, thats a better note :D

**Comment by jkakar** [comment]
:+1: Thank you!

**Comment by coryodaniel** [comment]
Just doing my part :P


No, thank you!

**Pull request merged**
